### ISSUE TITLE
Problems running  "rollup -c rollup.js"

### ISSUE THREAD

**Issue by manuelmejiaio** [JuanDelgadillo/angular2-pokedex#6]
When npm install try to run rollup -c rollup.js , it try to open the file in a program for no reason and then it can't finish the installation :

![capture](https://cloud.githubusercontent.com/assets/2773793/19934511/36cc7368-a0ed-11e6-92b3-3984ca6116c5.PNG)

**Comment by JuanDelgadillo** [comment]
The mean reason is because npm scripts don't work very well on Windows at all, so you have to change the npm script in package.json: 
`"rollup": "rollup -c rollup.js",`
to:
`"rollup": "node ./node_modules/rollup/bin/rollup -c rollup.js",`

Then try `npm install` again to let it finish the process and finally when you run `npm start` it should work fine. 

Now I've changed the rollup npmscript to work fine on windows/Osx/Linux.
